# in this yaml you should add dependencies that are not included in the python packages
# (or that you want to install anyways such as torch to install cuda w/ conda)
# also make sure to install the local packages with the "-e" prefix
# to create an environment: conda env create -f environment.yaml
# to update: conda env update -f environment.yaml
name: cloth-competition-dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg
  - x265
  - jupyter
  - pip
  - pip:
      - numpy
      - matplotlib
      - scipy
      - pytest
      - pre-commit
      - mypy
      - darglint
      - drake
      - "ffmpegcv"
      - "ur-analytic-ik == 0.0.3"
      - "airo-typing @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-typing"
      - "airo-spatial-algebra @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-spatial-algebra"
      - "airo-robots @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-robots"
      - "airo-camera-toolkit @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-camera-toolkit"
      - "airo-dataset-tools @ git+https://github.com/airo-ugent/airo-mono@main#subdirectory=airo-dataset-tools"
      - "linen @ git+https://github.com/Victorlouisdg/linen@main#subdirectory=linen"
      - -e cloth-tools/
