name: static type checking

on:
  pull_request:
  push:
    branches:
      - main
      - ci-dev

jobs:
  mypy:
    name: Run MyPy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: install conda env with micromamba
      uses: mamba-org/setup-micromamba@v1.7.3
      with:
        environment-file: environment.yaml
        cache-environment: true
    - name: Conda list
      shell: bash -l {0}
      run: conda list
    - name: Run type checker
      shell: bash -l {0}
      run: |
        mypy --version & mypy .