name: Pytest

on:
  pull_request:
  push:
    branches: [main,ci-dev]

jobs:
  test-multi-os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # test other OSs even if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: install conda env with micromamba
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          environment-file: environment.yaml
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Micromamba list
        shell: bash -l {0}
        run: micromamba list
      - name: pytest
        shell: bash -l {0}
        run: pytest .