name: Pytest

on:
  pull_request:
  push:
    branches: [main,ci-dev]

jobs:
  test-multi-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # , macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: install conda env with micromamba
        uses: mamba-org/setup-micromamba@v1.7.3
        with:
          environment-file: environment.yaml
          cache-environment: true
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: pytest
        shell: bash -l {0}
        run: |
          pytest .